/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BirminghamRouteImport } from './routes/birmingham'
import { Route as BuhlRouteImport } from './routes/buhl'
import { Route as CommercialElectricalRouteImport } from './routes/commercial-electrical'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ElectricalRepairsRouteImport } from './routes/electrical-repairs'
import { Route as NorthportRouteImport } from './routes/northport'
import { Route as OutdoorWiringRouteImport } from './routes/outdoor-wiring'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TuscaloosaRouteImport } from './routes/tuscaloosa'
import { Route as WiringUpgradesRouteImport } from './routes/wiring-upgrades'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BirminghamRoute = BirminghamRouteImport.update({
  id: '/birmingham',
  path: '/birmingham',
  getParentRoute: () => rootRouteImport,
} as any)
const BuhlRoute = BuhlRouteImport.update({
  id: '/buhl',
  path: '/buhl',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialElectricalRoute = CommercialElectricalRouteImport.update({
  id: '/commercial-electrical',
  path: '/commercial-electrical',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricalRepairsRoute = ElectricalRepairsRouteImport.update({
  id: '/electrical-repairs',
  path: '/electrical-repairs',
  getParentRoute: () => rootRouteImport,
} as any)
const NorthportRoute = NorthportRouteImport.update({
  id: '/northport',
  path: '/northport',
  getParentRoute: () => rootRouteImport,
} as any)
const OutdoorWiringRoute = OutdoorWiringRouteImport.update({
  id: '/outdoor-wiring',
  path: '/outdoor-wiring',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TuscaloosaRoute = TuscaloosaRouteImport.update({
  id: '/tuscaloosa',
  path: '/tuscaloosa',
  getParentRoute: () => rootRouteImport,
} as any)
const WiringUpgradesRoute = WiringUpgradesRouteImport.update({
  id: '/wiring-upgrades',
  path: '/wiring-upgrades',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/birmingham': typeof BirminghamRoute
  '/buhl': typeof BuhlRoute
  '/commercial-electrical': typeof CommercialElectricalRoute
  '/contact': typeof ContactRoute
  '/electrical-repairs': typeof ElectricalRepairsRoute
  '/northport': typeof NorthportRoute
  '/outdoor-wiring': typeof OutdoorWiringRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tuscaloosa': typeof TuscaloosaRoute
  '/wiring-upgrades': typeof WiringUpgradesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/birmingham': typeof BirminghamRoute
  '/buhl': typeof BuhlRoute
  '/commercial-electrical': typeof CommercialElectricalRoute
  '/contact': typeof ContactRoute
  '/electrical-repairs': typeof ElectricalRepairsRoute
  '/northport': typeof NorthportRoute
  '/outdoor-wiring': typeof OutdoorWiringRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tuscaloosa': typeof TuscaloosaRoute
  '/wiring-upgrades': typeof WiringUpgradesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/birmingham': typeof BirminghamRoute
  '/buhl': typeof BuhlRoute
  '/commercial-electrical': typeof CommercialElectricalRoute
  '/contact': typeof ContactRoute
  '/electrical-repairs': typeof ElectricalRepairsRoute
  '/northport': typeof NorthportRoute
  '/outdoor-wiring': typeof OutdoorWiringRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tuscaloosa': typeof TuscaloosaRoute
  '/wiring-upgrades': typeof WiringUpgradesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/birmingham'
    | '/buhl'
    | '/commercial-electrical'
    | '/contact'
    | '/electrical-repairs'
    | '/northport'
    | '/outdoor-wiring'
    | '/reviews'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/tuscaloosa'
    | '/wiring-upgrades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/birmingham'
    | '/buhl'
    | '/commercial-electrical'
    | '/contact'
    | '/electrical-repairs'
    | '/northport'
    | '/outdoor-wiring'
    | '/reviews'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/tuscaloosa'
    | '/wiring-upgrades'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/birmingham'
    | '/buhl'
    | '/commercial-electrical'
    | '/contact'
    | '/electrical-repairs'
    | '/northport'
    | '/outdoor-wiring'
    | '/reviews'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/tuscaloosa'
    | '/wiring-upgrades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BirminghamRoute: typeof BirminghamRoute
  BuhlRoute: typeof BuhlRoute
  CommercialElectricalRoute: typeof CommercialElectricalRoute
  ContactRoute: typeof ContactRoute
  ElectricalRepairsRoute: typeof ElectricalRepairsRoute
  NorthportRoute: typeof NorthportRoute
  OutdoorWiringRoute: typeof OutdoorWiringRoute
  ReviewsRoute: typeof ReviewsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TuscaloosaRoute: typeof TuscaloosaRoute
  WiringUpgradesRoute: typeof WiringUpgradesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birmingham': {
      id: '/birmingham'
      path: '/birmingham'
      fullPath: '/birmingham'
      preLoaderRoute: typeof BirminghamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buhl': {
      id: '/buhl'
      path: '/buhl'
      fullPath: '/buhl'
      preLoaderRoute: typeof BuhlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-electrical': {
      id: '/commercial-electrical'
      path: '/commercial-electrical'
      fullPath: '/commercial-electrical'
      preLoaderRoute: typeof CommercialElectricalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrical-repairs': {
      id: '/electrical-repairs'
      path: '/electrical-repairs'
      fullPath: '/electrical-repairs'
      preLoaderRoute: typeof ElectricalRepairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/northport': {
      id: '/northport'
      path: '/northport'
      fullPath: '/northport'
      preLoaderRoute: typeof NorthportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outdoor-wiring': {
      id: '/outdoor-wiring'
      path: '/outdoor-wiring'
      fullPath: '/outdoor-wiring'
      preLoaderRoute: typeof OutdoorWiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuscaloosa': {
      id: '/tuscaloosa'
      path: '/tuscaloosa'
      fullPath: '/tuscaloosa'
      preLoaderRoute: typeof TuscaloosaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiring-upgrades': {
      id: '/wiring-upgrades'
      path: '/wiring-upgrades'
      fullPath: '/wiring-upgrades'
      preLoaderRoute: typeof WiringUpgradesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BirminghamRoute: BirminghamRoute,
  BuhlRoute: BuhlRoute,
  CommercialElectricalRoute: CommercialElectricalRoute,
  ContactRoute: ContactRoute,
  ElectricalRepairsRoute: ElectricalRepairsRoute,
  NorthportRoute: NorthportRoute,
  OutdoorWiringRoute: OutdoorWiringRoute,
  ReviewsRoute: ReviewsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TuscaloosaRoute: TuscaloosaRoute,
  WiringUpgradesRoute: WiringUpgradesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
