/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WiringUpgradesTuscaloosaAlRouteImport } from './routes/wiring-upgrades-tuscaloosa-al'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as OutdoorWiringTuscaloosaAlRouteImport } from './routes/outdoor-wiring-tuscaloosa-al'
import { Route as ElectricianTuscaloosaAlRouteImport } from './routes/electrician-tuscaloosa-al'
import { Route as ElectricianNorthportAlRouteImport } from './routes/electrician-northport-al'
import { Route as ElectricianBirminghamAlRouteImport } from './routes/electrician-birmingham-al'
import { Route as ElectricalRepairsTuscaloosaAlRouteImport } from './routes/electrical-repairs-tuscaloosa-al'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommercialElectricalTuscaloosaAlRouteImport } from './routes/commercial-electrical-tuscaloosa-al'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WiringUpgradesTuscaloosaAlRoute =
  WiringUpgradesTuscaloosaAlRouteImport.update({
    id: '/wiring-upgrades-tuscaloosa-al',
    path: '/wiring-upgrades-tuscaloosa-al',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const OutdoorWiringTuscaloosaAlRoute =
  OutdoorWiringTuscaloosaAlRouteImport.update({
    id: '/outdoor-wiring-tuscaloosa-al',
    path: '/outdoor-wiring-tuscaloosa-al',
    getParentRoute: () => rootRouteImport,
  } as any)
const ElectricianTuscaloosaAlRoute = ElectricianTuscaloosaAlRouteImport.update({
  id: '/electrician-tuscaloosa-al',
  path: '/electrician-tuscaloosa-al',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricianNorthportAlRoute = ElectricianNorthportAlRouteImport.update({
  id: '/electrician-northport-al',
  path: '/electrician-northport-al',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricianBirminghamAlRoute = ElectricianBirminghamAlRouteImport.update({
  id: '/electrician-birmingham-al',
  path: '/electrician-birmingham-al',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricalRepairsTuscaloosaAlRoute =
  ElectricalRepairsTuscaloosaAlRouteImport.update({
    id: '/electrical-repairs-tuscaloosa-al',
    path: '/electrical-repairs-tuscaloosa-al',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialElectricalTuscaloosaAlRoute =
  CommercialElectricalTuscaloosaAlRouteImport.update({
    id: '/commercial-electrical-tuscaloosa-al',
    path: '/commercial-electrical-tuscaloosa-al',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial-electrical-tuscaloosa-al': typeof CommercialElectricalTuscaloosaAlRoute
  '/contact': typeof ContactRoute
  '/electrical-repairs-tuscaloosa-al': typeof ElectricalRepairsTuscaloosaAlRoute
  '/electrician-birmingham-al': typeof ElectricianBirminghamAlRoute
  '/electrician-northport-al': typeof ElectricianNorthportAlRoute
  '/electrician-tuscaloosa-al': typeof ElectricianTuscaloosaAlRoute
  '/outdoor-wiring-tuscaloosa-al': typeof OutdoorWiringTuscaloosaAlRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wiring-upgrades-tuscaloosa-al': typeof WiringUpgradesTuscaloosaAlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial-electrical-tuscaloosa-al': typeof CommercialElectricalTuscaloosaAlRoute
  '/contact': typeof ContactRoute
  '/electrical-repairs-tuscaloosa-al': typeof ElectricalRepairsTuscaloosaAlRoute
  '/electrician-birmingham-al': typeof ElectricianBirminghamAlRoute
  '/electrician-northport-al': typeof ElectricianNorthportAlRoute
  '/electrician-tuscaloosa-al': typeof ElectricianTuscaloosaAlRoute
  '/outdoor-wiring-tuscaloosa-al': typeof OutdoorWiringTuscaloosaAlRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wiring-upgrades-tuscaloosa-al': typeof WiringUpgradesTuscaloosaAlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial-electrical-tuscaloosa-al': typeof CommercialElectricalTuscaloosaAlRoute
  '/contact': typeof ContactRoute
  '/electrical-repairs-tuscaloosa-al': typeof ElectricalRepairsTuscaloosaAlRoute
  '/electrician-birmingham-al': typeof ElectricianBirminghamAlRoute
  '/electrician-northport-al': typeof ElectricianNorthportAlRoute
  '/electrician-tuscaloosa-al': typeof ElectricianTuscaloosaAlRoute
  '/outdoor-wiring-tuscaloosa-al': typeof OutdoorWiringTuscaloosaAlRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wiring-upgrades-tuscaloosa-al': typeof WiringUpgradesTuscaloosaAlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/commercial-electrical-tuscaloosa-al'
    | '/contact'
    | '/electrical-repairs-tuscaloosa-al'
    | '/electrician-birmingham-al'
    | '/electrician-northport-al'
    | '/electrician-tuscaloosa-al'
    | '/outdoor-wiring-tuscaloosa-al'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/wiring-upgrades-tuscaloosa-al'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/commercial-electrical-tuscaloosa-al'
    | '/contact'
    | '/electrical-repairs-tuscaloosa-al'
    | '/electrician-birmingham-al'
    | '/electrician-northport-al'
    | '/electrician-tuscaloosa-al'
    | '/outdoor-wiring-tuscaloosa-al'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/wiring-upgrades-tuscaloosa-al'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/commercial-electrical-tuscaloosa-al'
    | '/contact'
    | '/electrical-repairs-tuscaloosa-al'
    | '/electrician-birmingham-al'
    | '/electrician-northport-al'
    | '/electrician-tuscaloosa-al'
    | '/outdoor-wiring-tuscaloosa-al'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/wiring-upgrades-tuscaloosa-al'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommercialElectricalTuscaloosaAlRoute: typeof CommercialElectricalTuscaloosaAlRoute
  ContactRoute: typeof ContactRoute
  ElectricalRepairsTuscaloosaAlRoute: typeof ElectricalRepairsTuscaloosaAlRoute
  ElectricianBirminghamAlRoute: typeof ElectricianBirminghamAlRoute
  ElectricianNorthportAlRoute: typeof ElectricianNorthportAlRoute
  ElectricianTuscaloosaAlRoute: typeof ElectricianTuscaloosaAlRoute
  OutdoorWiringTuscaloosaAlRoute: typeof OutdoorWiringTuscaloosaAlRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WiringUpgradesTuscaloosaAlRoute: typeof WiringUpgradesTuscaloosaAlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiring-upgrades-tuscaloosa-al': {
      id: '/wiring-upgrades-tuscaloosa-al'
      path: '/wiring-upgrades-tuscaloosa-al'
      fullPath: '/wiring-upgrades-tuscaloosa-al'
      preLoaderRoute: typeof WiringUpgradesTuscaloosaAlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outdoor-wiring-tuscaloosa-al': {
      id: '/outdoor-wiring-tuscaloosa-al'
      path: '/outdoor-wiring-tuscaloosa-al'
      fullPath: '/outdoor-wiring-tuscaloosa-al'
      preLoaderRoute: typeof OutdoorWiringTuscaloosaAlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrician-tuscaloosa-al': {
      id: '/electrician-tuscaloosa-al'
      path: '/electrician-tuscaloosa-al'
      fullPath: '/electrician-tuscaloosa-al'
      preLoaderRoute: typeof ElectricianTuscaloosaAlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrician-northport-al': {
      id: '/electrician-northport-al'
      path: '/electrician-northport-al'
      fullPath: '/electrician-northport-al'
      preLoaderRoute: typeof ElectricianNorthportAlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrician-birmingham-al': {
      id: '/electrician-birmingham-al'
      path: '/electrician-birmingham-al'
      fullPath: '/electrician-birmingham-al'
      preLoaderRoute: typeof ElectricianBirminghamAlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrical-repairs-tuscaloosa-al': {
      id: '/electrical-repairs-tuscaloosa-al'
      path: '/electrical-repairs-tuscaloosa-al'
      fullPath: '/electrical-repairs-tuscaloosa-al'
      preLoaderRoute: typeof ElectricalRepairsTuscaloosaAlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-electrical-tuscaloosa-al': {
      id: '/commercial-electrical-tuscaloosa-al'
      path: '/commercial-electrical-tuscaloosa-al'
      fullPath: '/commercial-electrical-tuscaloosa-al'
      preLoaderRoute: typeof CommercialElectricalTuscaloosaAlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommercialElectricalTuscaloosaAlRoute: CommercialElectricalTuscaloosaAlRoute,
  ContactRoute: ContactRoute,
  ElectricalRepairsTuscaloosaAlRoute: ElectricalRepairsTuscaloosaAlRoute,
  ElectricianBirminghamAlRoute: ElectricianBirminghamAlRoute,
  ElectricianNorthportAlRoute: ElectricianNorthportAlRoute,
  ElectricianTuscaloosaAlRoute: ElectricianTuscaloosaAlRoute,
  OutdoorWiringTuscaloosaAlRoute: OutdoorWiringTuscaloosaAlRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WiringUpgradesTuscaloosaAlRoute: WiringUpgradesTuscaloosaAlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
